# Generated by Django 3.1 on 2020-09-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200825_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='access',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
