# Generated by Django 3.1 on 2021-08-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffId', models.CharField(max_length=10)),
                ('companyId', models.CharField(max_length=50, null=True)),
                ('branchId', models.CharField(max_length=50, null=True)),
                ('permission', models.CharField(max_length=30)),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='updated')),
            ],
        ),
    ]
