# Generated by Django 3.1 on 2021-04-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='net_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
