# Generated by Django 3.1 on 2021-07-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_attender'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cost_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
    ]
