# Generated by Django 3.1 on 2020-09-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='toPay',
            field=models.IntegerField(default=0),
        ),
    ]
