# Generated by Django 3.1 on 2021-04-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20210403_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='disccount',
        ),
    ]
