# Generated by Django 3.1 on 2021-04-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_remove_sale_disccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='invoiceId',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
