# Generated by Django 3.1 on 2021-06-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_sale_disccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='disccount',
            new_name='discount',
        ),
    ]
