# Generated by Django 3.1 on 2021-07-19 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20210622_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cost_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='selling_price',
            field=models.IntegerField(default=0),
        ),
    ]
