# Generated by Django 3.1 on 2020-08-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='expenses',
            new_name='expense',
        ),
    ]
