# Generated by Django 3.1 on 2020-08-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='branches',
            name='state',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='branches',
            name='street',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='branches',
            name='town',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
