# Generated by Django 3.1 on 2020-08-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_auto_20200824_0947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='branches',
            new_name='branch',
        ),
    ]
