# Generated by Django 3.1 on 2020-09-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_auto_20200826_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branchId',
            field=models.CharField(max_length=20),
        ),
    ]
