# Generated by Django 3.1 on 2021-07-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0005_auto_20200912_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(default='here', max_length=300),
            preserve_default=False,
        ),
    ]
