# Generated by Django 3.1 on 2020-08-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=50)),
                ('productId', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
                ('batchId', models.CharField(max_length=10)),
                ('expiryDate', models.DateField(blank=True)),
                ('unit', models.CharField(max_length=10)),
                ('ppmu', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('expDate', models.DateField()),
            ],
        ),
    ]
