# Generated by Django 3.1 on 2021-07-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_stock_expdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='batchId',
            field=models.CharField(max_length=30),
        ),
    ]
