# Generated by Django 3.1 on 2020-08-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='branchId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='companyId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
