# Generated by Django 3.1 on 2021-08-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='storageId',
            field=models.CharField(default='heelo', max_length=200),
            preserve_default=False,
        ),
    ]
