# Generated by Django 3.1 on 2020-08-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_emailvalidated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='is_phonevalidated',
            field=models.BooleanField(default=False),
        ),
    ]
