# Generated by Django 3.1 on 2020-10-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201006_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='expiration_limit',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='stock_limit',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
