# Generated by Django 3.1 on 2021-09-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201031_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='download_access',
            field=models.BooleanField(default=False),
        ),
    ]
