# Generated by Django 3.1 on 2020-09-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='debtClearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('invoiceId', models.CharField(max_length=50, null=True)),
                ('paid', models.IntegerField()),
                ('companyId', models.CharField(max_length=50, null=True)),
                ('branchId', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
