# Generated by Django 3.1 on 2021-04-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debtclearance', '0002_auto_20210405_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtclearance',
            name='attender',
            field=models.CharField(default='william Ikeji', max_length=200),
            preserve_default=False,
        ),
    ]
