# Generated by Django 3.1 on 2020-08-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0002_auto_20200824_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
