# Generated by Django 3.1 on 2020-09-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0004_auto_20200825_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='invoiceId',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
