# Generated by Django 3.1 on 2020-08-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=20)),
                ('detail', models.CharField(max_length=200)),
                ('editor', models.CharField(max_length=50)),
                ('editorId', models.CharField(max_length=20)),
                ('batchId', models.CharField(max_length=20)),
            ],
        ),
    ]
