# Generated by Django 3.1 on 2020-09-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockActivities', '0003_auto_20200825_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockactivity',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
