# Generated by Django 3.1 on 2021-07-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockActivities', '0004_stockactivity_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockactivity',
            name='batchId',
        ),
    ]
