# Generated by Django 3.1 on 2021-07-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockActivities', '0005_remove_stockactivity_batchid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockactivity',
            name='activity',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='stockactivity',
            name='editor',
            field=models.CharField(max_length=200),
        ),
    ]
