# Generated by Django 3.1 on 2021-07-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20210708_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
