# Generated by Django 3.1 on 2021-07-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_pricing_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='daily_charge',
            field=models.IntegerField(default=0),
        ),
    ]
