# Generated by Django 3.1 on 2020-08-24 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='companies',
            new_name='company',
        ),
    ]
