# Generated by Django 3.1 on 2020-10-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_company_expirydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='branches',
            field=models.IntegerField(default=0),
        ),
    ]
